# Generated by Django 5.1.6 on 2025-02-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='alumni',
            field=models.ManyToManyField(blank=True, null=True, related_name='alumnis_club', to='shared.alumni'),
        ),
        migrations.AlterField(
            model_name='club',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
