# Generated by Django 5.1.6 on 2025-02-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_club_alumni_alter_club_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='alumni',
            field=models.ManyToManyField(blank=True, related_name='alumnis_club', to='shared.alumni'),
        ),
    ]
