# Generated by Django 5.1.6 on 2025-02-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='author',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
    ]
