# Generated by Django 5.1.6 on 2025-02-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_alter_club_user_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='agenda_events',
            field=models.ManyToManyField(null=True, related_name='students_agenda', to='shared.event'),
        ),
        migrations.AlterField(
            model_name='student',
            name='club_joined',
            field=models.ManyToManyField(null=True, related_name='students_joined', to='shared.club'),
        ),
        migrations.AlterField(
            model_name='student',
            name='club_suivi',
            field=models.ManyToManyField(null=True, related_name='students_suivi', to='shared.club'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roadmap_enroll',
            field=models.ManyToManyField(null=True, related_name='students_enrolled', to='shared.roadmap'),
        ),
    ]
